services:
  - type: web
    name: kamil-toporek-portfolio
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SENDGRID_API_KEY
        sync: false
      - key: EMAIL_USER
        sync: false
